/*
 * File name: TypeDef.h.
 * Function: Basic type defination of data type, which is based on the HM TypeDef.h.
 * Author: Ylonge from MCL-ZJU.
 * Date: 2015/11/17.
 */
#pragma once

// ====================================================================================================================
// Basic type redefinition
// ====================================================================================================================

typedef       void                Void;
typedef       bool                Bool;

typedef       char                Char;
typedef       unsigned char       UChar;
typedef       short               Short;
typedef       unsigned short      UShort;
typedef       int                 Int;
typedef       unsigned int        UInt;
typedef       double              Double;
typedef       float               Float;

// ====================================================================================================================
// 64-bit integer type
// ====================================================================================================================

//#ifdef _MSC_VER
//typedef       __int64             Int64;
//
//#if _MSC_VER <= 1200 // MS VC6
//typedef       __int64             UInt64;   // MS VC6 does not support unsigned __int64 to double conversion
//#else
//typedef       unsigned __int64    UInt64;
//#endif
//
//#else
//
//typedef       long long           Int64;
//typedef       unsigned long long  UInt64;
//
//#endif

// ====================================================================================================================
// Type definition
// ====================================================================================================================

typedef       UChar           Pxl;        ///< 8-bit pixel type
typedef       Short           Pel;        ///< 16-bit pixel type
typedef       Int             TCoeff;     ///< transform coefficient

// ====================================================================================================================
// Constant definition
// ====================================================================================================================

#define MAX_NUM_CHAR_NAME    1000
#define MAX_NUM_ENC_QP       4

// ====================================================================================================================
// Switch of alternative algorithms.
// ====================================================================================================================

#define HM_LOG 1     ///< The log file is generated by HM codec.


// ====================================================================================================================
// Simple Functions.
// ====================================================================================================================

#define Max(a, b) (a > b ? a : b)
#define Min(a, b) (a < b ? a : b)

// ====================================================================================================================
// Switch of Debug.
// ====================================================================================================================

/************************************************************************/
/* Enum Lists
/************************************************************************/
// Types of Codecs.
enum EnumTypeOfCodec
{
	CODEC_HM = 0,
	CODEC_LIBVC = 1,
	NUM_CODEC = 2
};

// Types of results
enum EnumTypeOfResult
{
	RESULT_TOTAL = 0,
	RESULT_PART = 1,
	RESULT_RANDOM_ACCESS = 2,
	NUM_RESULT = 3
};